config/routes.rb
UniqCheck::Application.routes.draw do
  resources :checklists

  root :to => "pages#intropage"
  
  match "/about" => "pages#about"
  match "/contact" => "pages#contact"
  match "/complete.json" => "checklists#complete"

end

app/models/check.rb
class Check < ActiveRecord::Base
  validates_presence_of :name
  belongs_to :checklist
end

app/models/checklist.rb
class Checklist < ActiveRecord::Base
  extend FriendlyId
  friendly_id :tag, use: :slugged
  
  
  validates_presence_of :name
  
  has_many :checks
  accepts_nested_attributes_for :checks, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController

  # GET /checklists/1
  # GET /checklists/1.json
  def show
    @checklist = Checklist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @checklist }
    end
  end

  # GET /checklists/new
  # GET /checklists/new.json
  def new
    @checklist = Checklist.new
    @checklist.checks.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @checklist }
    end
  end

  # GET /checklists/1/edit
  def edit
    @checklist = Checklist.find(params[:id])
    @checklist.checks.build
  end

  # POST /checklists
  # POST /checklists.json
  def create
    @checklist = Checklist.new(params[:checklist])
    
    random_string = ActiveSupport::SecureRandom.hex(5)
    while Checklist.find_by_tag(random_string) != nil
      random_string = ActiveSupport::SecureRandom.hex(5)
    end
    @checklist.tag = random_string
    
    respond_to do |format|
      if @checklist.save
        format.html { redirect_to @checklist, notice: 'Checklist was successfully created.' }
        format.json { render json: @checklist, status: :created, location: @checklist }
      else
        format.html { render action: "new" }
        format.json { render json: @checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checklists/1
  # PUT /checklists/1.json
  def update
    @checklist = Checklist.find(params[:id])

    respond_to do |format|
      if @checklist.update_attributes(params[:checklist])
        format.html { redirect_to @checklist, notice: 'Checklist was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @checklist.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def complete
    @check = Check.find(params[:id])
    if @check.completed == true
      @check.completed = false
    else
      @check.completed = true
    end
    @check.save
    render :nothing => true
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def intropage
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/checklists/_check_fields.html.erb
<div class="field">
	<br />
	<%= f.text_field :name %>
	<%= f.hidden_field :_destroy %>
	<%= link_to_function "remove", "remove_fields(this)"%>
</div>

app/views/checklists/_form.html.erb
<%= form_for(@checklist) do |f| %>
  <% if @checklist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checklist.errors.count, "error") %> prohibited this checklist from being saved:</h2>

      <ul>
      <% @checklist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<br />
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
    <%= f.fields_for :checks do |builder| %>
		<%= render "check_fields", :f => builder %>
	<% end %>
	<br />
	<%= link_to_add_fields "Add Todo", f, :checks %>
	<br />
	<br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checklists/edit.html.erb
<h1>Editing checklist</h1>

<%= render 'form' %>

<%= link_to 'Back', @checklist %>

app/views/checklists/new.html.erb
<h1>New checklist</h1>

<%= render 'form' %>

<%= link_to 'Back', @checklist %>

app/views/checklists/show.html.erb
<% if notice %>
<div class="notice"><%= notice %></div>
<% end %>
<br />
<br />
<h1>
  <%= @checklist.name %>
</h1>
<br />
<p>
  <b>Share link:</b> 
  http://uniqcheck.heroku.com/checklists/<%= @checklist.tag %>
<br /><br />
<b><%= mail_to "", "Email this checklist.",
         :subject => "Someone shared an checklist with you on UniqCheck!", :body => "Hey, come check out this checklist I made." %></b>
</p>
<br />
<h4>Things to do:</h4><br />
<% @checklist.checks.each do |check| %>
<%= check_box_tag '', value ="1", check.completed, :class => "complete", :id => check.id %>&nbsp;&nbsp;
<%= check.name %><br /><br />
<% end %>
<br />
<%= link_to 'Add more todos', edit_checklist_path(@checklist) %>
<script>

$(".complete").click(function() {
	var id = $(this).attr('id');
	$.ajax({
			type: "POST",
	        url: '/complete.json',
			data: 'id=' + id,
	        async: false
	});
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UniqCheck</title>
	<meta name="keywords" content="checklist, checklist online, online checklist, uniqcheck, unique check" >
	<meta name="description" content="Make checklists for personal and team use easily. No logins required." >
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>

	<style type="text/css">a { color: #FF9933;} a:hover { color: #FF9933; }</style>
  <%= csrf_meta_tags %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30317823-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</head>
<body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
			<%= link_to "UniqCheck", { :controller => "pages", :action => "intropage" }, :class => "brand" %>
            <ul class="nav">
              <li class="active"><%= link_to "Home", :controller => "pages", :action => "intropage" %></li>
              <li><%= link_to "About", :controller => "pages", :action => "about" %></li>
              <li><%= link_to "Contact", :controller => "pages", :action => "contact" %></li>
            </ul>
			<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4f6d72ea31b4d77e"></script>
			<!-- AddThis Button END -->
        </div>
      </div>
    </div>

    <div class="container" style ="padding-top:60px">


		<%= yield %>
    </div> 
	<div class="addthis">
	<!-- AddThis Button BEGIN -->
	<div class="addthis_toolbox addthis_default_style ">
	<a class="addthis_button_preferred_1"></a>
	<a class="addthis_button_preferred_2"></a>
	<a class="addthis_button_preferred_3"></a>
	<a class="addthis_button_preferred_4"></a>
	<a class="addthis_button_compact"></a>
	<a class="addthis_counter addthis_bubble_style"></a>
	</div>
	</div>
<br /><br /><br />
</body>
</html>

app/views/pages/about.html.erb
UniqCheck is a utility to make checklists and share them with your friends,<br />
or just use them for yourself.
<br />
<br />
Create a checklist and use the URL to access it. Note that this means checklists<br />
are somewhat public and can be altered (although unlikely).
<br />

app/views/pages/contact.html.erb
Contact me at <%= mail_to "dylandrop@gmail.com", "dylandrop@gmail.com" %>.

app/views/pages/intropage.html.erb
<center>
	
<h1>Welcome to UniqCheck. Generate a checklist, and share it with your friends.</h1> <br /><br />
<%= image_tag "512px-Black_check.png", :style => "width:250px" %><br /><br />
No login required. <br /><br />
</center>
<h1>
<center><%= link_to 'Make a new checklist.', new_checklist_path %></h1></center>